// @flow
import markdownTable from 'markdown-table'

import type { ReportSpec, FilesMetricsMap } from './config'

import { FILES_SUM_METRIC_KEY } from './config'

const metricsFor = (metricKeys: string[], record: Object) =>
  metricKeys.map(metric => record[metric] || '-')

export const markdownAllTable = (specMetricKeys: string[], all: Object) => {
  const metricKeys = [FILES_SUM_METRIC_KEY, ...specMetricKeys]

  const headers = metricKeys

  const rows = metricsFor(specMetricKeys, all)

  return markdownTable([headers, rows])
}

export const markdownOwnersTable = (
  specMetricKeys: string[],
  byOwner: Object,
) => {
  const metricKeys = [FILES_SUM_METRIC_KEY, ...specMetricKeys]

  const headers = ['owner', ...metricKeys]

  const rows = Object.keys(byOwner).map(owner => [
    owner,
    ...metricsFor(metricKeys, byOwner[owner]),
  ])

  return markdownTable([headers, ...rows])
}

export const markdownFileTable = (
  metricKeys: string[],
  byFile: FilesMetricsMap,
) => {
  const headers = ['filename', ...metricKeys]

  const rows = Object.keys(byFile).map(filename => [
    filename,
    ...metricsFor(metricKeys, byFile[filename]),
  ])

  return markdownTable([headers, ...rows])
}

/**
 * Format the report as Markdown text
 */
export const formatReport = (reportSpec: ReportSpec, report: *) => {
  const specMetricKeys = [
    ...Object.keys(reportSpec.regexpMetrics || {}),
    ...Object.keys(reportSpec.eslintFlags || {}),
  ]

  const content = [
    'This report was autogenerated by code-owners-report.\n\n',
    '## All files',
    markdownAllTable(specMetricKeys, report.byAll),
    '## By owner (non-exclusive)',
    report.byOwner
      ? markdownOwnersTable(specMetricKeys, report.byOwner)
      : 'Missing CODEOWNERS',
    '## Each file',
    markdownFileTable(specMetricKeys, report.byFile),
    '\n',
  ].join('\n\n')

  return content
}
