// @flow
import markdownTable from 'markdown-table'

import type { ReportSpec, FilesMetricsMap } from './config'

const metricsFor = (metricKeys: string[], record: Object) =>
  metricKeys.map(metric => record[metric] || '-')

export const markdownAllTable = (metricKeys: string[], all: Object) => {
  const headers = metricKeys
  const rows = metricsFor(metricKeys, all)
  return markdownTable([headers, rows])
}

export const markdownOwnersTable = (metricKeys: string[], byOwner: Object) => {
  const headers = ['owner', ...metricKeys]

  const rows = Object.keys(byOwner).map(owner => [
    owner,
    ...metricsFor(metricKeys, byOwner[owner]),
  ])

  return markdownTable([headers, ...rows])
}

export const markdownFileTable = (
  metricKeys: string[],
  byFile: FilesMetricsMap,
) => {
  const headers = ['filename', ...metricKeys]

  const rows = Object.keys(byFile).map(filename => [
    filename,
    ...metricsFor(metricKeys, byFile[filename]),
  ])

  return markdownTable([headers, ...rows])
}

/**
 * Format the report as Markdown text
 */
export const formatReport = (reportSpec: ReportSpec, report: *) => {
  const metricKeys = [
    ...Object.keys(reportSpec.regexpMetrics || {}),
    ...Object.keys(reportSpec.eslintFlags || {}),
  ]

  const content = [
    'This report was autogenerated by code-owners-report.\n\n',
    markdownAllTable(metricKeys, report.byAll),
    report.byOwner
      ? markdownOwnersTable(metricKeys, report.byOwner)
      : 'Missing CODEOWNERS',
    markdownFileTable(metricKeys, report.byFile),
    '\n',
  ].join('\n\n')

  return content
}
